{
  "name": "Corona",
  "compatibilityLevel": 1560,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "dataSources": [
      {
        "name": "MKServer Corona",
        "connectionString": "Data Source=MKServer;Initial Catalog=Corona;Integrated Security=True;Persist Security Info=True",
        "impersonationMode": "impersonateServiceAccount",
        "provider": "System.Data.SqlClient"
      }
    ],
    "tables": [
      {
        "name": "Calendar",
        "lineageTag": "37fd7966-9dbb-49a3-8d90-351de4b9987c",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "CalendarId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarId",
            "lineageTag": "19662dab-6926-4553-8fb4-ea7a61c4a0f1"
          },
          {
            "name": "Calendar Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "CalendarDate",
            "lineageTag": "6b264273-2521-4ccb-a213-0f2f33171114"
          },
          {
            "name": "Calendar Month",
            "dataType": "dateTime",
            "sourceColumn": "CalendarMonth",
            "formatString": "mmmm YYYY",
            "lineageTag": "cceca245-622a-4da5-a5c3-99fd7c492efe"
          },
          {
            "name": "Today Flag",
            "dataType": "string",
            "sourceColumn": "TodayFlag",
            "lineageTag": "4c58bf37-7325-4074-bbfc-536c6a5e2ce1"
          },
          {
            "name": "Time Reference Flag",
            "dataType": "string",
            "sourceColumn": "TimeReferenceFlag",
            "lineageTag": "36723ac0-ac11-4003-924d-aabf068d2a32"
          },
          {
            "name": "Data Start Flag",
            "dataType": "string",
            "sourceColumn": "DataStartFlag",
            "lineageTag": "94d01bec-31b7-4e22-a10a-72e9a84a634a"
          },
          {
            "name": "Data End Flag",
            "dataType": "string",
            "sourceColumn": "DataEndFlag",
            "lineageTag": "4444422c-9f52-4d89-942e-bb549aed8f02"
          },
          {
            "name": "Data Available Flag",
            "dataType": "string",
            "sourceColumn": "DataAvailableFlag",
            "lineageTag": "652644ed-ea63-43a1-93de-644c1e7ebda1"
          },
          {
            "name": "Last 5 Days Flag",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Last5DaysFlag",
            "lineageTag": "22c2f899-532d-47f2-a8e6-3f1902bba051"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[DIM_Calendar]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "lineageTag": "81c14fb4-2879-4b1b-abb7-1e0e2d5dc15c",
            "levels": [
              {
                "name": "Calendar Month",
                "ordinal": 0,
                "column": "Calendar Month",
                "lineageTag": "3fb69541-c982-4db0-9e2c-7694902716ea"
              },
              {
                "name": "Calendar Date",
                "ordinal": 1,
                "column": "Calendar Date",
                "lineageTag": "2946548b-e2a2-49c8-972b-47ceea025b78"
              }
            ]
          }
        ]
      },
      {
        "name": "Geography",
        "lineageTag": "e33bf58e-58d2-4b3e-a69f-2ce1d0eeb867",
        "columns": [
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "lineageTag": "b9404b81-023a-4c8b-b055-9c460c38dc4a"
          },
          {
            "name": "Province",
            "dataType": "string",
            "sourceColumn": "Province_State",
            "lineageTag": "5003e0ba-e2d1-40c9-8a47-df9103b46307"
          },
          {
            "name": "GeographyId",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "GeographyId",
            "lineageTag": "4d30b14a-efe2-4926-b23b-4cf306ec2e1d"
          },
          {
            "name": "Top Case Country Flag",
            "dataType": "string",
            "sourceColumn": "TopCaseCountryFlag",
            "lineageTag": "4e72100e-dba5-4f7b-8ad0-830573888e12"
          },
          {
            "name": "Population",
            "dataType": "int64",
            "sourceColumn": "CountryPopulation",
            "formatString": "#,0",
            "lineageTag": "daae24cb-ec71-4680-92c0-5728fa938131",
            "summarizeBy": "none"
          },
          {
            "name": "US State Population",
            "dataType": "int64",
            "sourceColumn": "USStatePopulation",
            "formatString": "#,0",
            "lineageTag": "cc38fd36-e14e-46d9-8e00-310920df193d",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "81786734-a986-4eee-9403-a5d5154a8b3a"
          },
          {
            "name": "Country Flag",
            "dataType": "string",
            "sourceColumn": "CountryFlag",
            "lineageTag": "3490c7c2-c119-43d4-ba36-b00e5fb7c537",
            "dataCategory": "ImageURL"
          },
          {
            "type": "calculated",
            "name": "Country 1",
            "dataType": "unknown",
            "isDataTypeInferred": true,
            "expression": "RELATED('Geography'[Country])",
            "lineageTag": "445f90d6-fab7-405c-87a6-4a6794bd416c"
          }
        ],
        "partitions": [
          {
            "name": "Geography",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[DIM_Geography]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Geography Hierarchy",
            "lineageTag": "71101301-d85d-46bb-b827-e1c40a68239f",
            "levels": [
              {
                "name": "Country",
                "ordinal": 0,
                "column": "Country",
                "lineageTag": "02e65cb5-6714-411a-af0f-18427a96627f"
              },
              {
                "name": "Province",
                "ordinal": 1,
                "column": "Province",
                "lineageTag": "06530d46-1b09-49b4-a421-c70020bbf904"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City",
                "lineageTag": "52193ee7-ee01-44b2-964a-7e059763dd8a"
              }
            ]
          }
        ]
      },
      {
        "name": "Corona",
        "description": "This table shows all COVID-19 case data.",
        "lineageTag": "3b2bca52-3c1b-42fa-b142-19fe6dcd9360",
        "columns": [
          {
            "name": "CalendarId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarId",
            "lineageTag": "7aed0d2c-8c50-4392-bd78-97450a54e84c"
          },
          {
            "name": "ConfirmedCount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ConfirmedCount",
            "lineageTag": "58460946-aa41-474e-90ab-c57755ea35e3"
          },
          {
            "name": "DeathsCount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DeathsCount",
            "lineageTag": "650355f2-d04c-4d06-b813-f5da56d3e2c8"
          },
          {
            "name": "ActiveCount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ActiveCount",
            "lineageTag": "a3424d9d-da29-44c8-b941-ef0dd1ea84f2"
          },
          {
            "name": "RecoveredCount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RecoveredCount",
            "lineageTag": "af21483b-99f1-4994-b143-4f391908d61f"
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude",
            "lineageTag": "bbd023a6-b5f0-46f6-9a1c-14a81b9bd932"
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude",
            "lineageTag": "74884589-8314-4a8c-b238-650f7c24cda4"
          },
          {
            "name": "GeographyId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyId",
            "lineageTag": "dd629ac4-a387-45cf-a94c-c75c7d36e345"
          },
          {
            "name": "LastUpdate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Last_Update",
            "lineageTag": "d2576df8-daf3-4fb7-b577-4d7b72c1dd27"
          }
        ],
        "partitions": [
          {
            "name": "Corona",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[FACT_Corona]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "measures": [
          {
            "name": "Deaths",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM('Corona'[DeathsCount]),    CALCULATE (        SUM('Corona'[DeathsCount]),        LASTNONBLANK ( 'Corona'[CalendarId], SUM('Corona'[DeathsCount]) )    ))",
            "formatString": "#,0",
            "lineageTag": "aefb3f30-fd60-41c9-9851-a8946fc1c07c"
          },
          {
            "name": "Active Cases",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM ( 'Corona'[ActiveCount] ),    CALCULATE (        SUM ( 'Corona'[ActiveCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[ActiveCount] ) )    ))",
            "formatString": "#,0",
            "lineageTag": "0fd0774d-4331-4b6f-9ef5-42b79da352e9"
          },
          {
            "name": "Cases",
            "description": "Shows the cumulative number of cases.",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM ( 'Corona'[ConfirmedCount] ),    CALCULATE (        SUM ( 'Corona'[ConfirmedCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[ConfirmedCount] ) )    ))",
            "formatString": "#,0",
            "lineageTag": "70866c8d-8328-4701-a8fa-1a1b0a735fe7"
          },
          {
            "name": "Recovered",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM ( 'Corona'[RecoveredCount] ),    CALCULATE (        SUM ( 'Corona'[RecoveredCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[RecoveredCount] ) )    ))",
            "formatString": "#,0",
            "lineageTag": "0a455dce-a1d7-4f5c-86eb-59cb8434af54"
          },
          {
            "name": "New Deaths",
            "expression": "VAR x =    CALCULATE ( [Deaths], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y = [Deaths]RETURN    IF ( NOT ( x = BLANK () || y = BLANK () ), y - x )",
            "formatString": "#,0",
            "displayFolder": "New",
            "lineageTag": "305023be-976c-4272-93ca-647e43e0825e"
          },
          {
            "name": "New Cases",
            "expression": "VAR x =    CALCULATE ( [Cases], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y = [Cases]RETURN    IF ( NOT ( x = BLANK () || y = BLANK () ), y - x )",
            "formatString": "#,0",
            "displayFolder": "New",
            "lineageTag": "ba65bd88-447c-409a-b37d-1a143ce22acd"
          },
          {
            "name": "New Recovered",
            "expression": "VAR x =    CALCULATE ( [Recovered], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y = [Recovered]RETURN    IF ( NOT ( x = BLANK () || y = BLANK () ), y - x )",
            "formatString": "#,0",
            "displayFolder": "New",
            "lineageTag": "9da5b092-84e5-4a28-96f5-84f8ee1741fc"
          },
          {
            "name": "New Case Growth Rate %",
            "expression": "VAR x =    CALCULATE ( [New Cases], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y =    [New Cases]RETURN    IF ( NOT ( y = BLANK () ), DIVIDE ( y - x, x ) )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Growth",
            "lineageTag": "2f9888f9-5973-48b6-ae52-7d1ac1cb45d5"
          },
          {
            "name": "Active Case Growth Rate %",
            "expression": "VAR x =    CALCULATE ( [Active Cases], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y =    [Active Cases]RETURN    IF ( NOT ( y = BLANK () ), DIVIDE ( y - x, x ) )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Growth",
            "lineageTag": "3e8226a8-1747-4fc5-a399-f319ec449de0"
          },
          {
            "name": "Cases Growth Rate %",
            "expression": "VAR x =    CALCULATE ( [Cases], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y =    [Cases]RETURN    IF ( NOT ( y = BLANK () ), DIVIDE ( y - x, x ) )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Growth",
            "lineageTag": "d6c3c7e3-d843-4565-88c6-4f319dd46ccd"
          },
          {
            "name": "Cases per 1M pop",
            "expression": "VAR num = [Cases]VAR denomcountry =    DIVIDE ( MIN ( 'Geography'[Population] ), 1000000 )VAR wppm = 7774VAR denomstate =    DIVIDE ( MIN ( 'Geography'[US State Population] ), 1000000 )VAR usppm = 331RETURN    IF (        ISFILTERED ( 'Geography'[Province] ),        IF (            HASONEVALUE ( 'Geography'[Province] ),            DIVIDE ( num, denomstate ),            DIVIDE ( num, usppm )        ),        IF (            HASONEVALUE ( 'Geography'[Country] ),            DIVIDE ( num, denomcountry ),            DIVIDE ( num, wppm )        )    )",
            "formatString": "#,0",
            "displayFolder": "Advanced",
            "lineageTag": "3e312e22-9a63-4d91-b9cb-8ca4245ef772"
          },
          {
            "name": "Days of Consecutive Neg Case Growth",
            "expression": "//VAR lastdayofincrease =//    CALCULATE (//        MAX ( 'Calendar'[Calendar Date] ),//        'Calendar'[Data Available Flag] = \"Yes\",//        FILTER (//            ALL ( 'Calendar' ),//            [Cases Growth Rate %]//                >= CALCULATE (//                    [Cases Growth Rate %],//                    DATEADD ( 'Calendar'[Calendar Date], -1, DAY )//                )//        )//    )VAR lastdayofincrease =    CALCULATE (        MAX ( 'Calendar'[Calendar Date] ),        'Calendar'[Data Available Flag] = \"Yes\",        FILTER (            ALL ( 'Calendar' ),            [New Cases]                >= CALCULATE (                    [New Cases],                    DATEADD ( 'Calendar'[Calendar Date], -1, DAY )                )        )    )    VAR lastday =    CALCULATE (        MAX ( 'Calendar'[Calendar Date] ),        FILTER (            ALL ( 'Calendar' ),            CALCULATE ( SUM ( 'Corona'[ConfirmedCount] ) > 0 )        )    )RETURN    DATEDIFF ( lastdayofincrease, lastday, DAY )",
            "formatString": "#,0",
            "displayFolder": "Advanced",
            "lineageTag": "0617c6c4-1617-4f0b-bce8-fc2355c8a80a"
          },
          {
            "name": "Death Rate %",
            "expression": "DIVIDE ( [Deaths], [Cases] )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "06c009ca-afed-4ae4-966a-c3c3934a257d"
          },
          {
            "name": "Recovered Rate %",
            "expression": "DIVIDE ( [Recovered], [Cases] )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "30a440bc-0a1b-499f-bfda-f7344e295bf6"
          },
          {
            "name": "Closed Cases",
            "expression": "[Recovered] + [Deaths]",
            "formatString": "#,0",
            "lineageTag": "6b11076c-6ca7-47fc-8692-eda760853c0f"
          },
          {
            "name": "Recovery Rate of Closed Cases %",
            "expression": "VAR num =    CALCULATE (        SUM ( 'Corona'[RecoveredCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[RecoveredCount] ) )    )VAR denom =    num        + CALCULATE (            SUM ( 'Corona'[DeathsCount] ),            LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[DeathsCount] ) )        )RETURN    DIVIDE ( num, denom )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "b89f8bb5-9e83-4822-ad7f-24754b9ba4ce"
          },
          {
            "name": "Death Rate of Closed Cases %",
            "expression": "VAR num =    CALCULATE (        SUM ( 'Corona'[DeathsCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[DeathsCount] ) )    )VAR denom =    num        + CALCULATE (            SUM ( 'Corona'[RecoveredCount] ),            LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[RecoveredCount] ) )        )RETURN    DIVIDE ( num, denom )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "73f775d3-63bc-4663-8f87-d06f711d6e26"
          },
          {
            "name": "Days Since Cases Last Doubled",
            "expression": "VAR lastday =    CALCULATE (        MAX ( 'Calendar'[Calendar Date] ),        FILTER (            ALL ( 'Calendar' ),            CALCULATE ( SUM ( 'Corona'[ConfirmedCount] ) > 0 )        )    )VAR mostrecentcases =    CALCULATE (        SUM ( 'Corona'[ConfirmedCount] ),        FILTER ( ALL ( 'Calendar' ), 'Calendar'[Calendar Date] = lastday )    )VAR x =    CALCULATE (        MAX ( 'Calendar'[Calendar Date] ),        'Calendar'[Data Available Flag] = \"Yes\",        FILTER ( ALL ( 'Calendar' ), [Cases] < ( mostrecentcases / 2 ) )    )RETURN    DATEDIFF ( x, lastday, DAY )",
            "formatString": "#,0",
            "displayFolder": "Advanced",
            "lineageTag": "203791f8-a185-4012-8c17-19b6f01bf36a"
          },
          {
            "name": "Last Updated",
            "expression": "MAX ( 'Corona'[LastUpdate] )",
            "lineageTag": "faaa1917-14f3-4c71-84ac-f13286a361c2"
          }
        ]
      },
      {
        "name": "Scale",
        "lineageTag": "58b71afd-f2c1-4ba9-beff-03968cc736f5",
        "columns": [
          {
            "name": "Scale Type",
            "dataType": "string",
            "sourceColumn": "ScaleType",
            "lineageTag": "a0b3bc6a-c6d4-49c0-860d-5ac8c0534829"
          },
          {
            "name": "CalendarId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarId",
            "lineageTag": "9d9ebef0-4fd3-492a-9e49-b325261d5de9"
          }
        ],
        "partitions": [
          {
            "name": "Scale",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[FACT_Scale]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "measures": [
          {
            "name": "ScaleSelection",
            "expression": "IF ( SELECTEDVALUE ( 'Scale'[Scale Type] ) = \"Linear\", 0, BLANK () )",
            "isHidden": true,
            "lineageTag": "3f0d5e98-81de-49f2-b713-2eeb5ca2b130"
          }
        ]
      },
      {
        "name": "Testing",
        "lineageTag": "e3a46082-2472-4cc9-b078-cf39d2b804a8",
        "columns": [
          {
            "name": "CalendarId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarId",
            "lineageTag": "a4a71e5c-e732-4cc6-8476-113b39b66dd1"
          },
          {
            "name": "GeographyId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyId",
            "lineageTag": "128261c0-0003-4d75-8e11-cebc44d6f448"
          },
          {
            "name": "Entity",
            "dataType": "string",
            "sourceColumn": "Entity",
            "lineageTag": "7131a1a9-474b-4233-9148-0a5002384f8d"
          },
          {
            "name": "CumulativeTotalTests",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CumulativeTotalTests",
            "lineageTag": "354d702c-8c48-4105-b49e-1d457ffc3486"
          }
        ],
        "partitions": [
          {
            "name": "Testing",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[FACT_Testing]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "measures": [
          {
            "name": "Cumulative Tests",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM ( 'Testing'[CumulativeTotalTests] ),    CALCULATE (        SUM ( 'Testing'[CumulativeTotalTests] ),        LASTNONBLANK ( 'Testing'[CalendarId], SUM ( 'Testing'[CumulativeTotalTests] ) )    ))",
            "formatString": "#,0",
            "lineageTag": "c6b76213-11f2-4b65-a7fa-9be517a8123a"
          },
          {
            "name": "Tests",
            "expression": "VAR x =    CALCULATE ( [Cumulative Tests], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y = [Cumulative Tests]RETURN    IF ( NOT ( x = BLANK () || y = BLANK () ), y - x )",
            "formatString": "#,0",
            "lineageTag": "632273fe-c9db-4b95-8c28-ecc83dcab366"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "d8aa53ec-5cf1-4474-9381-63c74e7afefa",
        "fromTable": "Corona",
        "fromColumn": "GeographyId",
        "toTable": "Geography",
        "toColumn": "GeographyId"
      },
      {
        "name": "e46fe1b7-41b2-461b-8ce0-75f4f1edd0df",
        "fromTable": "Corona",
        "fromColumn": "CalendarId",
        "toTable": "Calendar",
        "toColumn": "CalendarId"
      },
      {
        "name": "0a8f6a0f-2df7-4b79-8f32-067e1aabc5d7",
        "fromTable": "Testing",
        "fromColumn": "GeographyId",
        "toTable": "Geography",
        "toColumn": "GeographyId"
      },
      {
        "name": "8837f3e1-b72d-49ce-a908-941fa1a94db1",
        "fromTable": "Testing",
        "fromColumn": "CalendarId",
        "toTable": "Calendar",
        "toColumn": "CalendarId"
      },
      {
        "name": "2200f9c1-9fb2-4dd2-a072-4980c2a1fa2d",
        "fromTable": "Scale",
        "fromColumn": "CalendarId",
        "toTable": "Calendar",
        "toColumn": "CalendarId"
      }
    ],
    "roles": [
      {
        "name": "Reader",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\alias1"
          }
        ],
        "tablePermissions": [
          {
            "name": "Geography",
            "filterExpression": "'Geography'[Country]=\"United States\""
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}