{
  "name": "Corona",
  "compatibilityLevel": 1560,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "dataSources": [
      {
        "name": "MKServer Corona",
        "connectionString": "Data Source=MKServer;Initial Catalog=Corona;Integrated Security=True;Persist Security Info=True",
        "impersonationMode": "impersonateServiceAccount",
        "provider": "System.Data.SqlClient"
      }
    ],
    "tables": [
      {
        "name": "Calendar",
        "lineageTag": "fcfde77c-5a53-4863-b970-7e269b9c1f82",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "CalendarId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarId",
            "lineageTag": "3d7ae815-4343-4233-9d99-4a26cb3ae36d"
          },
          {
            "name": "Calendar Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "CalendarDate",
            "lineageTag": "ace18f2e-396e-4795-b012-e62b490fcd52"
          },
          {
            "name": "Calendar Month",
            "dataType": "dateTime",
            "sourceColumn": "CalendarMonth",
            "formatString": "mmmm YYYY",
            "lineageTag": "2dede388-c81f-4dcc-b616-78effa89c254"
          },
          {
            "name": "Today Flag",
            "dataType": "string",
            "sourceColumn": "TodayFlag",
            "lineageTag": "5842847a-b91a-4d9a-b589-0e313371f663"
          },
          {
            "name": "Time Reference Flag",
            "dataType": "string",
            "sourceColumn": "TimeReferenceFlag",
            "lineageTag": "d18abe39-3e99-4dbc-88e6-eb5147399c74"
          },
          {
            "name": "Data Start Flag",
            "dataType": "string",
            "sourceColumn": "DataStartFlag",
            "lineageTag": "0e746443-380f-465c-933a-8ad3ce950520"
          },
          {
            "name": "Data End Flag",
            "dataType": "string",
            "sourceColumn": "DataEndFlag",
            "lineageTag": "b462a8d9-e857-4d03-bad9-256af9bb7479"
          },
          {
            "name": "Data Available Flag",
            "dataType": "string",
            "sourceColumn": "DataAvailableFlag",
            "lineageTag": "6ac4b33a-156f-40c9-9ed7-eef1fce47f12"
          },
          {
            "name": "Last 5 Days Flag",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Last5DaysFlag",
            "lineageTag": "df0c87dc-c0f9-4600-a402-41df695b4d17"
          }
        ],
        "partitions": [
          {
            "name": "Calendar",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[DIM_Calendar]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "lineageTag": "9e3ff36f-addd-4ddd-adf2-2ee4f5120272",
            "levels": [
              {
                "name": "Calendar Month",
                "ordinal": 0,
                "column": "Calendar Month",
                "lineageTag": "a3954b6e-62e0-4c62-bdd8-6f70893e229d"
              },
              {
                "name": "Calendar Date",
                "ordinal": 1,
                "column": "Calendar Date",
                "lineageTag": "b5e006dc-4253-4d2b-a418-c5a2a22d7484"
              }
            ]
          }
        ]
      },
      {
        "name": "Geography",
        "lineageTag": "5e54bd31-ef97-4bf9-b2ff-5e299081267d",
        "columns": [
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country",
            "lineageTag": "1f4cac88-e84b-4606-801b-639ca287e3ba"
          },
          {
            "name": "Province",
            "dataType": "string",
            "sourceColumn": "Province_State",
            "lineageTag": "3179f50a-4bd7-4b48-88c6-a5e56a43256a"
          },
          {
            "name": "GeographyId",
            "dataType": "int64",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "GeographyId",
            "lineageTag": "036858d7-3f39-4ad5-8afc-ffb370306379"
          },
          {
            "name": "Top Case Country Flag",
            "dataType": "string",
            "sourceColumn": "TopCaseCountryFlag",
            "lineageTag": "18169bc8-2cb8-45ec-aa72-7e734643483c"
          },
          {
            "name": "Population",
            "dataType": "int64",
            "sourceColumn": "CountryPopulation",
            "formatString": "#,0",
            "lineageTag": "2f875d3f-aed7-46db-810e-3954a104f0ce",
            "summarizeBy": "none"
          },
          {
            "name": "US State Population",
            "dataType": "int64",
            "sourceColumn": "USStatePopulation",
            "formatString": "#,0",
            "lineageTag": "0f58e820-c539-4f4d-bc9d-c77d05cc477e",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "6da656a0-8390-46ed-a4eb-c12a83ba2a72"
          },
          {
            "name": "Country Flag",
            "dataType": "string",
            "sourceColumn": "CountryFlag",
            "lineageTag": "4d5da5d1-50e2-4f33-bc51-b811a4432ed4",
            "dataCategory": "ImageURL"
          },
          {
            "type": "calculated",
            "name": "Country 1",
            "dataType": "unknown",
            "isDataTypeInferred": true,
            "expression": "RELATED('Geography'[Country])",
            "lineageTag": "47898360-b53e-461b-ac48-f27351e02faf"
          }
        ],
        "partitions": [
          {
            "name": "Geography",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[DIM_Geography]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Geography Hierarchy",
            "lineageTag": "c1717c39-8267-40ce-8b52-2869af242966",
            "levels": [
              {
                "name": "Country",
                "ordinal": 0,
                "column": "Country",
                "lineageTag": "c6b729db-7c1b-4f12-98f1-74e056ef8119"
              },
              {
                "name": "Province",
                "ordinal": 1,
                "column": "Province",
                "lineageTag": "50835958-d371-4497-99dc-f7d8755abccb"
              },
              {
                "name": "City",
                "ordinal": 2,
                "column": "City",
                "lineageTag": "1eb3edeb-1791-4564-8f97-454348896f82"
              }
            ]
          }
        ]
      },
      {
        "name": "Corona",
        "description": "This table shows all COVID-19 case data.",
        "lineageTag": "7d0b5eec-8924-4688-9a8c-df3d9e7fe4fd",
        "columns": [
          {
            "name": "CalendarId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarId",
            "lineageTag": "6f969ad9-997f-4802-8d38-795aeedf9e61"
          },
          {
            "name": "ConfirmedCount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ConfirmedCount",
            "lineageTag": "252d6d8f-9872-4b71-8daa-0397a78c50c5"
          },
          {
            "name": "DeathsCount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "DeathsCount",
            "lineageTag": "72b48e90-ee83-498d-92d3-4e46495f4c1c"
          },
          {
            "name": "ActiveCount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "ActiveCount",
            "lineageTag": "ea5785de-9949-422b-8c1e-a8546c90ebeb"
          },
          {
            "name": "RecoveredCount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "RecoveredCount",
            "lineageTag": "b9ee9527-2e4a-4454-8210-ae4013ca9ebe"
          },
          {
            "name": "Longitude",
            "dataType": "double",
            "sourceColumn": "Longitude",
            "lineageTag": "9d32aaca-200b-4dae-9c94-c1f75a4cb381"
          },
          {
            "name": "Latitude",
            "dataType": "double",
            "sourceColumn": "Latitude",
            "lineageTag": "3c0e20f7-751c-48f0-8dc7-072044a8dca5"
          },
          {
            "name": "GeographyId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyId",
            "lineageTag": "b523f4a1-e179-4073-88f6-a18282d1a4a5"
          },
          {
            "name": "LastUpdate",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Last_Update",
            "lineageTag": "43d8a603-4afc-42ec-8e5a-32ea2901a239"
          }
        ],
        "partitions": [
          {
            "name": "Corona",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[FACT_Corona]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "measures": [
          {
            "name": "Deaths",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM('Corona'[DeathsCount]),    CALCULATE (        SUM('Corona'[DeathsCount]),        LASTNONBLANK ( 'Corona'[CalendarId], SUM('Corona'[DeathsCount]) )    ))",
            "formatString": "#,0",
            "lineageTag": "0d2572e1-ee3f-4692-8f86-747d15327bd4"
          },
          {
            "name": "Active Cases",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM ( 'Corona'[ActiveCount] ),    CALCULATE (        SUM ( 'Corona'[ActiveCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[ActiveCount] ) )    ))",
            "formatString": "#,0",
            "lineageTag": "3912c0e7-98f2-461f-9f36-0ba6c2c2f5a9"
          },
          {
            "name": "Cases",
            "description": "Shows the cumulative number of cases.",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM ( 'Corona'[ConfirmedCount] ),    CALCULATE (        SUM ( 'Corona'[ConfirmedCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[ConfirmedCount] ) )    ))",
            "formatString": "#,0",
            "lineageTag": "ad578e4c-111f-42a6-95fb-19abb88f3169"
          },
          {
            "name": "Recovered",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM ( 'Corona'[RecoveredCount] ),    CALCULATE (        SUM ( 'Corona'[RecoveredCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[RecoveredCount] ) )    ))",
            "formatString": "#,0",
            "lineageTag": "6a60fa0f-ee46-4df3-873f-8f187489a633"
          },
          {
            "name": "New Deaths",
            "expression": "VAR x =    CALCULATE ( [Deaths], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y = [Deaths]RETURN    IF ( NOT ( x = BLANK () || y = BLANK () ), y - x )",
            "formatString": "#,0",
            "displayFolder": "New",
            "lineageTag": "de280830-3285-4cca-9eea-8a4dcd19cf67"
          },
          {
            "name": "New Cases",
            "expression": "VAR x =    CALCULATE ( [Cases], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y = [Cases]RETURN    IF ( NOT ( x = BLANK () || y = BLANK () ), y - x )",
            "formatString": "#,0",
            "displayFolder": "New",
            "lineageTag": "2c31179b-8f0e-41c1-8dc5-3d03bf517148"
          },
          {
            "name": "New Recovered",
            "expression": "VAR x =    CALCULATE ( [Recovered], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y = [Recovered]RETURN    IF ( NOT ( x = BLANK () || y = BLANK () ), y - x )",
            "formatString": "#,0",
            "displayFolder": "New",
            "lineageTag": "aadf5e0f-ad00-484c-8ddc-14403956443a"
          },
          {
            "name": "New Case Growth Rate %",
            "expression": "VAR x =    CALCULATE ( [New Cases], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y =    [New Cases]RETURN    IF ( NOT ( y = BLANK () ), DIVIDE ( y - x, x ) )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Growth",
            "lineageTag": "e774890c-01e7-462d-a89c-7ebd440f5c49"
          },
          {
            "name": "Active Case Growth Rate %",
            "expression": "VAR x =    CALCULATE ( [Active Cases], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y =    [Active Cases]RETURN    IF ( NOT ( y = BLANK () ), DIVIDE ( y - x, x ) )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Growth",
            "lineageTag": "bebc404e-ea13-47b4-b508-1a15c33749ce"
          },
          {
            "name": "Cases Growth Rate %",
            "expression": "VAR x =    CALCULATE ( [Cases], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y =    [Cases]RETURN    IF ( NOT ( y = BLANK () ), DIVIDE ( y - x, x ) )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Growth",
            "lineageTag": "6a7b6534-e74e-4174-b44e-82b757798268"
          },
          {
            "name": "Cases per 1M pop",
            "expression": "VAR num = [Cases]VAR denomcountry =    DIVIDE ( MIN ( 'Geography'[Population] ), 1000000 )VAR wppm = 7774VAR denomstate =    DIVIDE ( MIN ( 'Geography'[US State Population] ), 1000000 )VAR usppm = 331RETURN    IF (        ISFILTERED ( 'Geography'[Province] ),        IF (            HASONEVALUE ( 'Geography'[Province] ),            DIVIDE ( num, denomstate ),            DIVIDE ( num, usppm )        ),        IF (            HASONEVALUE ( 'Geography'[Country] ),            DIVIDE ( num, denomcountry ),            DIVIDE ( num, wppm )        )    )",
            "formatString": "#,0",
            "displayFolder": "Advanced",
            "lineageTag": "0e842cc0-fe50-4063-93d2-d389538252d8"
          },
          {
            "name": "Days of Consecutive Neg Case Growth",
            "expression": "//VAR lastdayofincrease =//    CALCULATE (//        MAX ( 'Calendar'[Calendar Date] ),//        'Calendar'[Data Available Flag] = \"Yes\",//        FILTER (//            ALL ( 'Calendar' ),//            [Cases Growth Rate %]//                >= CALCULATE (//                    [Cases Growth Rate %],//                    DATEADD ( 'Calendar'[Calendar Date], -1, DAY )//                )//        )//    )VAR lastdayofincrease =    CALCULATE (        MAX ( 'Calendar'[Calendar Date] ),        'Calendar'[Data Available Flag] = \"Yes\",        FILTER (            ALL ( 'Calendar' ),            [New Cases]                >= CALCULATE (                    [New Cases],                    DATEADD ( 'Calendar'[Calendar Date], -1, DAY )                )        )    )    VAR lastday =    CALCULATE (        MAX ( 'Calendar'[Calendar Date] ),        FILTER (            ALL ( 'Calendar' ),            CALCULATE ( SUM ( 'Corona'[ConfirmedCount] ) > 0 )        )    )RETURN    DATEDIFF ( lastdayofincrease, lastday, DAY )",
            "formatString": "#,0",
            "displayFolder": "Advanced",
            "lineageTag": "691c068e-fdd0-4f45-9c7a-32176582c862"
          },
          {
            "name": "Death Rate %",
            "expression": "DIVIDE ( [Deaths], [Cases] )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "682e92dc-5828-4292-ba77-35d0b91fc5f6"
          },
          {
            "name": "Recovered Rate %",
            "expression": "DIVIDE ( [Recovered], [Cases] )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "147079dc-8278-4fd3-bd48-867b2e7ad543"
          },
          {
            "name": "Closed Cases",
            "expression": "[Recovered] + [Deaths]",
            "formatString": "#,0",
            "lineageTag": "3fef1fb6-e6d8-4074-b25b-906eeb16c8d2"
          },
          {
            "name": "Recovery Rate of Closed Cases %",
            "expression": "VAR num =    CALCULATE (        SUM ( 'Corona'[RecoveredCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[RecoveredCount] ) )    )VAR denom =    num        + CALCULATE (            SUM ( 'Corona'[DeathsCount] ),            LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[DeathsCount] ) )        )RETURN    DIVIDE ( num, denom )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "62f5bf8d-0cd2-4321-913c-a24c0bd4edfb"
          },
          {
            "name": "Death Rate of Closed Cases %",
            "expression": "VAR num =    CALCULATE (        SUM ( 'Corona'[DeathsCount] ),        LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[DeathsCount] ) )    )VAR denom =    num        + CALCULATE (            SUM ( 'Corona'[RecoveredCount] ),            LASTNONBLANK ( 'Corona'[CalendarId], SUM ( 'Corona'[RecoveredCount] ) )        )RETURN    DIVIDE ( num, denom )",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "lineageTag": "afa76317-62bd-4951-a424-98cd99083ea3"
          },
          {
            "name": "Days Since Cases Last Doubled",
            "expression": "VAR lastday =    CALCULATE (        MAX ( 'Calendar'[Calendar Date] ),        FILTER (            ALL ( 'Calendar' ),            CALCULATE ( SUM ( 'Corona'[ConfirmedCount] ) > 0 )        )    )VAR mostrecentcases =    CALCULATE (        SUM ( 'Corona'[ConfirmedCount] ),        FILTER ( ALL ( 'Calendar' ), 'Calendar'[Calendar Date] = lastday )    )VAR x =    CALCULATE (        MAX ( 'Calendar'[Calendar Date] ),        'Calendar'[Data Available Flag] = \"Yes\",        FILTER ( ALL ( 'Calendar' ), [Cases] < ( mostrecentcases / 2 ) )    )RETURN    DATEDIFF ( x, lastday, DAY )",
            "formatString": "#,0",
            "displayFolder": "Advanced",
            "lineageTag": "e4fafb17-7118-4cbb-a62c-27723a6abd2e"
          },
          {
            "name": "Last Updated",
            "expression": "MAX ( 'Corona'[LastUpdate] )",
            "lineageTag": "53c40be4-e463-457d-93a4-ac905277e650"
          }
        ]
      },
      {
        "name": "Scale",
        "lineageTag": "a6aa2acf-0afe-4784-a55e-69bc14594fdc",
        "columns": [
          {
            "name": "Scale Type",
            "dataType": "string",
            "sourceColumn": "ScaleType",
            "lineageTag": "3080c3ad-1a9e-46d8-95b1-f78a015be80c"
          },
          {
            "name": "CalendarId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarId",
            "lineageTag": "346a5a31-9ad3-4f51-9df3-550b30c3da21"
          }
        ],
        "partitions": [
          {
            "name": "Scale",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[FACT_Scale]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "measures": [
          {
            "name": "ScaleSelection",
            "expression": "IF ( SELECTEDVALUE ( 'Scale'[Scale Type] ) = \"Linear\", 0, BLANK () )",
            "isHidden": true,
            "lineageTag": "ffd9740a-2f4f-474f-9d6d-392e979a4edb"
          }
        ]
      },
      {
        "name": "Testing",
        "lineageTag": "e3605d64-c285-4d04-9a4e-75d7008b8408",
        "columns": [
          {
            "name": "CalendarId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CalendarId",
            "lineageTag": "b999782f-4801-46c2-9d04-9368173a0a25"
          },
          {
            "name": "GeographyId",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "GeographyId",
            "lineageTag": "9570669a-2b1f-4b2e-982d-4527bdebdbe6"
          },
          {
            "name": "Entity",
            "dataType": "string",
            "sourceColumn": "Entity",
            "lineageTag": "ad77f28c-2076-45c6-acbf-3e0b0309ec58"
          },
          {
            "name": "CumulativeTotalTests",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CumulativeTotalTests",
            "lineageTag": "0ebbfe17-f7cf-4c41-b823-9ed5e2d0b10a"
          }
        ],
        "partitions": [
          {
            "name": "Testing",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [CoronaView].[FACT_Testing]",
              "dataSource": "MKServer Corona"
            }
          }
        ],
        "measures": [
          {
            "name": "Cumulative Tests",
            "expression": "IF (    HASONEVALUE ( 'Calendar'[Calendar Date] ),    SUM ( 'Testing'[CumulativeTotalTests] ),    CALCULATE (        SUM ( 'Testing'[CumulativeTotalTests] ),        LASTNONBLANK ( 'Testing'[CalendarId], SUM ( 'Testing'[CumulativeTotalTests] ) )    ))",
            "formatString": "#,0",
            "lineageTag": "9c320d81-3d35-49d1-a36d-45f608be80df"
          },
          {
            "name": "Tests",
            "expression": "VAR x =    CALCULATE ( [Cumulative Tests], DATEADD ( 'Calendar'[Calendar Date], -1, DAY ) )VAR y = [Cumulative Tests]RETURN    IF ( NOT ( x = BLANK () || y = BLANK () ), y - x )",
            "formatString": "#,0",
            "lineageTag": "87c8a364-9182-4d27-b2a8-dac4cf0c8784"
          }
        ]
      },
      {
        "name": "Calc_table",
        "lineageTag": "af982ff6-7d73-43e2-b502-cd12d721b470",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": false,
            "sourceColumn": "[Value]",
            "lineageTag": "7b1a9f59-ebaa-4d8d-8042-f9f0836d4b74"
          },
          {
            "type": "calculated",
            "name": "cal_column",
            "dataType": "int64",
            "expression": "CALCULATE (SUM ( Corona[Longitude] ))",
            "lineageTag": "69ad7b4a-83fa-4dc6-aa16-374a547c0985"
          }
        ],
        "partitions": [
          {
            "name": "Calc_table",
            "mode": "import",
            "source": {
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calc_table1",
        "lineageTag": "5ddb863f-0539-4907-9994-d1cf1bfec542",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": false,
            "sourceColumn": "[Value]",
            "lineageTag": "90aa32ec-a169-421d-a4b1-fae35af23381"
          }
        ],
        "partitions": [
          {
            "name": "Calc_table1",
            "mode": "import",
            "source": {
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Calc_table2",
        "lineageTag": "eb7b3735-584c-47f3-b7cc-846059f6e002",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": false,
            "sourceColumn": "[Value]",
            "lineageTag": "5f738572-9749-46b1-a8de-6d1492f3cd5c"
          }
        ],
        "partitions": [
          {
            "name": "Calc_table2",
            "mode": "import",
            "source": {
              "type": "calculated"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "48bc07f9-1248-4b3b-a68d-5b573ea5ea9f",
        "fromTable": "Corona",
        "fromColumn": "GeographyId",
        "toTable": "Geography",
        "toColumn": "GeographyId"
      },
      {
        "name": "6f2db051-bf9f-4724-9151-07416291451a",
        "fromTable": "Corona",
        "fromColumn": "CalendarId",
        "toTable": "Calendar",
        "toColumn": "CalendarId"
      },
      {
        "name": "266694f4-78b8-4d2d-aa8e-2821672fa374",
        "fromTable": "Testing",
        "fromColumn": "GeographyId",
        "toTable": "Geography",
        "toColumn": "GeographyId"
      },
      {
        "name": "d0729dfe-a069-4725-8420-6d1fb7e926a3",
        "fromTable": "Testing",
        "fromColumn": "CalendarId",
        "toTable": "Calendar",
        "toColumn": "CalendarId"
      },
      {
        "name": "b23c2ef8-ffc6-4160-b2e4-e18fb61f1d05",
        "fromTable": "Scale",
        "fromColumn": "CalendarId",
        "toTable": "Calendar",
        "toColumn": "CalendarId"
      }
    ],
    "roles": [
      {
        "name": "Reader",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\alias1"
          }
        ],
        "tablePermissions": [
          {
            "name": "Geography",
            "filterExpression": "'Geography'[Country]=\"United States\""
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}